# Generated by Django 3.1.5 on 2021-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('passeword', models.CharField(max_length=20)),
            ],
        ),
    ]
