# Generated by Django 3.1.5 on 2021-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
